export const URLS = {
  login: '/login',
  register: '/register',
  sendEmail: '/register/sendEmail',
  password: '/password',
  users: '/users',
  specialties: '/specialties',
  categories: '/categories',
  attachments: '/attachments',
  comments: '/comments',
  modules: '/modules',
  publications: '/publications',
  chat: '/chat',
  opinion: '/opinions',
  friend: '/friends',
  room: '/room',
  messages: '/messages',
  roomUsers: '/roomUsers',
  isRegistred: '/isRegistred',
  markBest: '/markBest'
};
